# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc  # type: ignore

from edg_core.edgir import elem_pb2 as elem__pb2
from edg_core.edgrpc import hdl_pb2 as hdl__pb2
from edg_core.edgir import ref_pb2 as ref__pb2
from edg_core.edgir import schema_pb2 as schema__pb2


class HdlInterfaceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClearCached = channel.unary_stream(
                '/edg.compiler.HdlInterface/ClearCached',
                request_serializer=hdl__pb2.ModuleName.SerializeToString,
                response_deserializer=ref__pb2.LibraryPath.FromString,
                )
        self.LibraryElementsInModule = channel.unary_stream(
                '/edg.compiler.HdlInterface/LibraryElementsInModule',
                request_serializer=hdl__pb2.ModuleName.SerializeToString,
                response_deserializer=ref__pb2.LibraryPath.FromString,
                )
        self.GetLibraryElement = channel.unary_unary(
                '/edg.compiler.HdlInterface/GetLibraryElement',
                request_serializer=hdl__pb2.LibraryRequest.SerializeToString,
                response_deserializer=schema__pb2.Library.NS.Val.FromString,
                )
        self.ElaborateGenerator = channel.unary_unary(
                '/edg.compiler.HdlInterface/ElaborateGenerator',
                request_serializer=hdl__pb2.GeneratorRequest.SerializeToString,
                response_deserializer=elem__pb2.HierarchyBlock.FromString,
                )


class HdlInterfaceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClearCached(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LibraryElementsInModule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLibraryElement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ElaborateGenerator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HdlInterfaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClearCached': grpc.unary_stream_rpc_method_handler(
                    servicer.ClearCached,
                    request_deserializer=hdl__pb2.ModuleName.FromString,
                    response_serializer=ref__pb2.LibraryPath.SerializeToString,
            ),
            'LibraryElementsInModule': grpc.unary_stream_rpc_method_handler(
                    servicer.LibraryElementsInModule,
                    request_deserializer=hdl__pb2.ModuleName.FromString,
                    response_serializer=ref__pb2.LibraryPath.SerializeToString,
            ),
            'GetLibraryElement': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLibraryElement,
                    request_deserializer=hdl__pb2.LibraryRequest.FromString,
                    response_serializer=schema__pb2.Library.NS.Val.SerializeToString,
            ),
            'ElaborateGenerator': grpc.unary_unary_rpc_method_handler(
                    servicer.ElaborateGenerator,
                    request_deserializer=hdl__pb2.GeneratorRequest.FromString,
                    response_serializer=elem__pb2.HierarchyBlock.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edg.compiler.HdlInterface', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HdlInterface(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClearCached(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/edg.compiler.HdlInterface/ClearCached',
            hdl__pb2.ModuleName.SerializeToString,
            ref__pb2.LibraryPath.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LibraryElementsInModule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/edg.compiler.HdlInterface/LibraryElementsInModule',
            hdl__pb2.ModuleName.SerializeToString,
            ref__pb2.LibraryPath.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLibraryElement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/edg.compiler.HdlInterface/GetLibraryElement',
            hdl__pb2.LibraryRequest.SerializeToString,
            schema__pb2.Library.NS.Val.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ElaborateGenerator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/edg.compiler.HdlInterface/ElaborateGenerator',
            hdl__pb2.GeneratorRequest.SerializeToString,
            elem__pb2.HierarchyBlock.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
