# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hdl.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from edg_core.edgir import schema_pb2 as schema__pb2
from edg_core.edgir import ref_pb2 as ref__pb2
from edg_core.edgir import elem_pb2 as elem__pb2
from edg_core.edgir import lit_pb2 as lit__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hdl.proto',
  package='edg.compiler',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\thdl.proto\x12\x0c\x65\x64g.compiler\x1a\x0cschema.proto\x1a\tref.proto\x1a\nelem.proto\x1a\tlit.proto\"\x1a\n\nModuleName\x12\x0c\n\x04name\x18\x01 \x01(\t\"H\n\x0eLibraryRequest\x12\x0f\n\x07modules\x18\x01 \x03(\t\x12%\n\x07\x65lement\x18\x02 \x01(\x0b\x32\x14.edg.ref.LibraryPath\"\xd9\x01\n\x10GeneratorRequest\x12\x0f\n\x07modules\x18\x01 \x03(\t\x12%\n\x07\x65lement\x18\x02 \x01(\x0b\x32\x14.edg.ref.LibraryPath\x12\n\n\x02\x66n\x18\x03 \x01(\t\x12\x34\n\x06values\x18\x04 \x03(\x0b\x32$.edg.compiler.GeneratorRequest.Value\x1aK\n\x05Value\x12 \n\x04path\x18\x01 \x01(\x0b\x32\x12.edg.ref.LocalPath\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.edg.lit.ValueLit2\x80\x02\n\x0cHdlInterface\x12M\n\x17LibraryElementsInModule\x12\x18.edg.compiler.ModuleName\x1a\x14.edg.ref.LibraryPath\"\x00\x30\x01\x12O\n\x11GetLibraryElement\x12\x1c.edg.compiler.LibraryRequest\x1a\x1a.edg.schema.Library.NS.Val\"\x00\x12P\n\x12\x45laborateGenerator\x12\x1e.edg.compiler.GeneratorRequest\x1a\x18.edg.elem.HierarchyBlock\"\x00\x62\x06proto3'
  ,
  dependencies=[schema__pb2.DESCRIPTOR,ref__pb2.DESCRIPTOR,elem__pb2.DESCRIPTOR,lit__pb2.DESCRIPTOR,])




_MODULENAME = _descriptor.Descriptor(
  name='ModuleName',
  full_name='edg.compiler.ModuleName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='edg.compiler.ModuleName.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=101,
)


_LIBRARYREQUEST = _descriptor.Descriptor(
  name='LibraryRequest',
  full_name='edg.compiler.LibraryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='modules', full_name='edg.compiler.LibraryRequest.modules', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='element', full_name='edg.compiler.LibraryRequest.element', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=175,
)


_GENERATORREQUEST_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='edg.compiler.GeneratorRequest.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='edg.compiler.GeneratorRequest.Value.path', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='edg.compiler.GeneratorRequest.Value.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=395,
)

_GENERATORREQUEST = _descriptor.Descriptor(
  name='GeneratorRequest',
  full_name='edg.compiler.GeneratorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='modules', full_name='edg.compiler.GeneratorRequest.modules', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='element', full_name='edg.compiler.GeneratorRequest.element', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fn', full_name='edg.compiler.GeneratorRequest.fn', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='values', full_name='edg.compiler.GeneratorRequest.values', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GENERATORREQUEST_VALUE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=395,
)

_LIBRARYREQUEST.fields_by_name['element'].message_type = ref__pb2._LIBRARYPATH
_GENERATORREQUEST_VALUE.fields_by_name['path'].message_type = ref__pb2._LOCALPATH
_GENERATORREQUEST_VALUE.fields_by_name['value'].message_type = lit__pb2._VALUELIT
_GENERATORREQUEST_VALUE.containing_type = _GENERATORREQUEST
_GENERATORREQUEST.fields_by_name['element'].message_type = ref__pb2._LIBRARYPATH
_GENERATORREQUEST.fields_by_name['values'].message_type = _GENERATORREQUEST_VALUE
DESCRIPTOR.message_types_by_name['ModuleName'] = _MODULENAME
DESCRIPTOR.message_types_by_name['LibraryRequest'] = _LIBRARYREQUEST
DESCRIPTOR.message_types_by_name['GeneratorRequest'] = _GENERATORREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModuleName = _reflection.GeneratedProtocolMessageType('ModuleName', (_message.Message,), {
  'DESCRIPTOR' : _MODULENAME,
  '__module__' : 'hdl_pb2'
  # @@protoc_insertion_point(class_scope:edg.compiler.ModuleName)
  })
_sym_db.RegisterMessage(ModuleName)

LibraryRequest = _reflection.GeneratedProtocolMessageType('LibraryRequest', (_message.Message,), {
  'DESCRIPTOR' : _LIBRARYREQUEST,
  '__module__' : 'hdl_pb2'
  # @@protoc_insertion_point(class_scope:edg.compiler.LibraryRequest)
  })
_sym_db.RegisterMessage(LibraryRequest)

GeneratorRequest = _reflection.GeneratedProtocolMessageType('GeneratorRequest', (_message.Message,), {

  'Value' : _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), {
    'DESCRIPTOR' : _GENERATORREQUEST_VALUE,
    '__module__' : 'hdl_pb2'
    # @@protoc_insertion_point(class_scope:edg.compiler.GeneratorRequest.Value)
    })
  ,
  'DESCRIPTOR' : _GENERATORREQUEST,
  '__module__' : 'hdl_pb2'
  # @@protoc_insertion_point(class_scope:edg.compiler.GeneratorRequest)
  })
_sym_db.RegisterMessage(GeneratorRequest)
_sym_db.RegisterMessage(GeneratorRequest.Value)



_HDLINTERFACE = _descriptor.ServiceDescriptor(
  name='HdlInterface',
  full_name='edg.compiler.HdlInterface',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=398,
  serialized_end=654,
  methods=[
  _descriptor.MethodDescriptor(
    name='LibraryElementsInModule',
    full_name='edg.compiler.HdlInterface.LibraryElementsInModule',
    index=0,
    containing_service=None,
    input_type=_MODULENAME,
    output_type=ref__pb2._LIBRARYPATH,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetLibraryElement',
    full_name='edg.compiler.HdlInterface.GetLibraryElement',
    index=1,
    containing_service=None,
    input_type=_LIBRARYREQUEST,
    output_type=schema__pb2._LIBRARY_NS_VAL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ElaborateGenerator',
    full_name='edg.compiler.HdlInterface.ElaborateGenerator',
    index=2,
    containing_service=None,
    input_type=_GENERATORREQUEST,
    output_type=elem__pb2._HIERARCHYBLOCK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HDLINTERFACE)

DESCRIPTOR.services_by_name['HdlInterface'] = _HDLINTERFACE

# @@protoc_insertion_point(module_scope)
