# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Mapping as typing___Mapping,
    MutableMapping as typing___MutableMapping,
    Optional as typing___Optional,
    Text as typing___Text,
    overload as typing___overload,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class Metadata(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Members(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        class NodeEntry(google___protobuf___message___Message):
            DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
            key: typing___Text = ...

            @property
            def value(self) -> type___Metadata: ...

            def __init__(self,
                *,
                key : typing___Optional[typing___Text] = None,
                value : typing___Optional[type___Metadata] = None,
                ) -> None: ...
            def HasField(self, field_name: typing_extensions___Literal[u"value",b"value"]) -> builtin___bool: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"key",b"key",u"value",b"value"]) -> None: ...
        type___NodeEntry = NodeEntry


        @property
        def node(self) -> typing___MutableMapping[typing___Text, type___Metadata]: ...

        def __init__(self,
            *,
            node : typing___Optional[typing___Mapping[typing___Text, type___Metadata]] = None,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"node",b"node"]) -> None: ...
    type___Members = Members

    known: typing___Text = ...
    text_leaf: typing___Text = ...
    bin_leaf: builtin___bytes = ...

    @property
    def unknown(self) -> type___Empty: ...

    @property
    def members(self) -> type___Metadata.Members: ...

    def __init__(self,
        *,
        unknown : typing___Optional[type___Empty] = None,
        known : typing___Optional[typing___Text] = None,
        members : typing___Optional[type___Metadata.Members] = None,
        text_leaf : typing___Optional[typing___Text] = None,
        bin_leaf : typing___Optional[builtin___bytes] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"bin_leaf",b"bin_leaf",u"known",b"known",u"members",b"members",u"meta",b"meta",u"text_leaf",b"text_leaf",u"type",b"type",u"unknown",b"unknown"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"bin_leaf",b"bin_leaf",u"known",b"known",u"members",b"members",u"meta",b"meta",u"text_leaf",b"text_leaf",u"type",b"type",u"unknown",b"unknown"]) -> None: ...
    @typing___overload
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"meta",b"meta"]) -> typing_extensions___Literal["members","text_leaf","bin_leaf"]: ...
    @typing___overload
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"type",b"type"]) -> typing_extensions___Literal["unknown","known"]: ...
type___Metadata = Metadata

class Empty(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    def __init__(self,
        ) -> None: ...
type___Empty = Empty
