# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Mapping as typing___Mapping,
    MutableMapping as typing___MutableMapping,
    NewType as typing___NewType,
    Optional as typing___Optional,
    Text as typing___Text,
    cast as typing___cast,
    overload as typing___overload,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class Metadata(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Members(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        class NodeEntry(google___protobuf___message___Message):
            DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
            key: typing___Text = ...

            @property
            def value(self) -> type___Metadata: ...

            def __init__(self,
                *,
                key : typing___Optional[typing___Text] = None,
                value : typing___Optional[type___Metadata] = None,
                ) -> None: ...
            def HasField(self, field_name: typing_extensions___Literal[u"value",b"value"]) -> builtin___bool: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"key",b"key",u"value",b"value"]) -> None: ...
        type___NodeEntry = NodeEntry


        @property
        def node(self) -> typing___MutableMapping[typing___Text, type___Metadata]: ...

        def __init__(self,
            *,
            node : typing___Optional[typing___Mapping[typing___Text, type___Metadata]] = None,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"node",b"node"]) -> None: ...
    type___Members = Members

    known: typing___Text = ...
    text_leaf: typing___Text = ...
    bin_leaf: builtin___bytes = ...

    @property
    def unknown(self) -> type___Empty: ...

    @property
    def members(self) -> type___Metadata.Members: ...

    @property
    def source_locator(self) -> type___SourceLocator: ...

    @property
    def namespace_order(self) -> type___NamespaceOrder: ...

    @property
    def error(self) -> type___Error: ...

    @property
    def copper_net(self) -> type___CopperNet: ...

    @property
    def footprint(self) -> type___Footprint: ...

    def __init__(self,
        *,
        unknown : typing___Optional[type___Empty] = None,
        known : typing___Optional[typing___Text] = None,
        members : typing___Optional[type___Metadata.Members] = None,
        text_leaf : typing___Optional[typing___Text] = None,
        bin_leaf : typing___Optional[builtin___bytes] = None,
        source_locator : typing___Optional[type___SourceLocator] = None,
        namespace_order : typing___Optional[type___NamespaceOrder] = None,
        error : typing___Optional[type___Error] = None,
        copper_net : typing___Optional[type___CopperNet] = None,
        footprint : typing___Optional[type___Footprint] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"bin_leaf",b"bin_leaf",u"copper_net",b"copper_net",u"error",b"error",u"footprint",b"footprint",u"known",b"known",u"members",b"members",u"meta",b"meta",u"namespace_order",b"namespace_order",u"source_locator",b"source_locator",u"text_leaf",b"text_leaf",u"type",b"type",u"unknown",b"unknown"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"bin_leaf",b"bin_leaf",u"copper_net",b"copper_net",u"error",b"error",u"footprint",b"footprint",u"known",b"known",u"members",b"members",u"meta",b"meta",u"namespace_order",b"namespace_order",u"source_locator",b"source_locator",u"text_leaf",b"text_leaf",u"type",b"type",u"unknown",b"unknown"]) -> None: ...
    @typing___overload
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"meta",b"meta"]) -> typing_extensions___Literal["members","text_leaf","bin_leaf","source_locator","namespace_order","error","copper_net","footprint"]: ...
    @typing___overload
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"type",b"type"]) -> typing_extensions___Literal["unknown","known"]: ...
type___Metadata = Metadata

class SourceLocator(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    SourceTypeValue = typing___NewType('SourceTypeValue', builtin___int)
    type___SourceTypeValue = SourceTypeValue
    SourceType: _SourceType
    class _SourceType(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[SourceLocator.SourceTypeValue]):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        UNKNOWN = typing___cast(SourceLocator.SourceTypeValue, 0)
        DEFINITION = typing___cast(SourceLocator.SourceTypeValue, 1)
        INSTANTIATION = typing___cast(SourceLocator.SourceTypeValue, 2)
    UNKNOWN = typing___cast(SourceLocator.SourceTypeValue, 0)
    DEFINITION = typing___cast(SourceLocator.SourceTypeValue, 1)
    INSTANTIATION = typing___cast(SourceLocator.SourceTypeValue, 2)
    type___SourceType = SourceType

    file_package: typing___Text = ...
    line_offset: builtin___int = ...
    col_offset: builtin___int = ...
    source_type: type___SourceLocator.SourceTypeValue = ...

    def __init__(self,
        *,
        file_package : typing___Optional[typing___Text] = None,
        line_offset : typing___Optional[builtin___int] = None,
        col_offset : typing___Optional[builtin___int] = None,
        source_type : typing___Optional[type___SourceLocator.SourceTypeValue] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"col_offset",b"col_offset",u"file_package",b"file_package",u"line_offset",b"line_offset",u"source_type",b"source_type"]) -> None: ...
type___SourceLocator = SourceLocator

class NamespaceOrder(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    names: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text] = ...

    def __init__(self,
        *,
        names : typing___Optional[typing___Iterable[typing___Text]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"names",b"names"]) -> None: ...
type___NamespaceOrder = NamespaceOrder

class Error(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    message: typing___Text = ...

    @property
    def source(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___SourceLocator]: ...

    def __init__(self,
        *,
        message : typing___Optional[typing___Text] = None,
        source : typing___Optional[typing___Iterable[type___SourceLocator]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"message",b"message",u"source",b"source"]) -> None: ...
type___Error = Error

class CopperNet(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    def __init__(self,
        ) -> None: ...
type___CopperNet = CopperNet

class Footprint(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class PinningEntry(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        key: typing___Text = ...
        value: typing___Text = ...

        def __init__(self,
            *,
            key : typing___Optional[typing___Text] = None,
            value : typing___Optional[typing___Text] = None,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"key",b"key",u"value",b"value"]) -> None: ...
    type___PinningEntry = PinningEntry

    refdes_prefix: typing___Text = ...
    footprint_name: typing___Text = ...
    part: typing___Text = ...
    manufacturer: typing___Text = ...
    value: typing___Text = ...

    @property
    def pinning(self) -> typing___MutableMapping[typing___Text, typing___Text]: ...

    def __init__(self,
        *,
        refdes_prefix : typing___Optional[typing___Text] = None,
        footprint_name : typing___Optional[typing___Text] = None,
        pinning : typing___Optional[typing___Mapping[typing___Text, typing___Text]] = None,
        part : typing___Optional[typing___Text] = None,
        manufacturer : typing___Optional[typing___Text] = None,
        value : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"footprint_name",b"footprint_name",u"manufacturer",b"manufacturer",u"part",b"part",u"pinning",b"pinning",u"refdes_prefix",b"refdes_prefix",u"value",b"value"]) -> None: ...
type___Footprint = Footprint

class Empty(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    def __init__(self,
        ) -> None: ...
type___Empty = Empty
