# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from .common_pb2 import (
    Empty as common_pb2___Empty,
    Metadata as common_pb2___Metadata,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class ValInit(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def floating(self) -> common_pb2___Empty: ...

    @property
    def integer(self) -> common_pb2___Empty: ...

    @property
    def boolean(self) -> common_pb2___Empty: ...

    @property
    def text(self) -> common_pb2___Empty: ...

    @property
    def set(self) -> common_pb2___Empty: ...

    @property
    def struct(self) -> common_pb2___Empty: ...

    @property
    def range(self) -> common_pb2___Empty: ...

    @property
    def meta(self) -> common_pb2___Metadata: ...

    def __init__(self,
        *,
        floating : typing___Optional[common_pb2___Empty] = None,
        integer : typing___Optional[common_pb2___Empty] = None,
        boolean : typing___Optional[common_pb2___Empty] = None,
        text : typing___Optional[common_pb2___Empty] = None,
        set : typing___Optional[common_pb2___Empty] = None,
        struct : typing___Optional[common_pb2___Empty] = None,
        range : typing___Optional[common_pb2___Empty] = None,
        meta : typing___Optional[common_pb2___Metadata] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"boolean",b"boolean",u"floating",b"floating",u"integer",b"integer",u"meta",b"meta",u"range",b"range",u"set",b"set",u"struct",b"struct",u"text",b"text",u"val",b"val"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"boolean",b"boolean",u"floating",b"floating",u"integer",b"integer",u"meta",b"meta",u"range",b"range",u"set",b"set",u"struct",b"struct",u"text",b"text",u"val",b"val"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"val",b"val"]) -> typing_extensions___Literal["floating","integer","boolean","text","set","struct","range"]: ...
type___ValInit = ValInit
