# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from .common_pb2 import (
    Metadata as common_pb2___Metadata,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
    Union as typing___Union,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode


class Namespace(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    basic = ... # type: typing___Text

    @property
    def meta(self) -> common_pb2___Metadata: ...

    def __init__(self,
        *,
        basic : typing___Optional[typing___Text] = None,
        meta : typing___Optional[common_pb2___Metadata] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> Namespace: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Namespace: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"basic",b"basic",u"meta",b"meta",u"namespace",b"namespace"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"basic",b"basic",u"meta",b"meta",u"namespace",b"namespace"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"namespace",b"namespace"]) -> typing_extensions___Literal["basic"]: ...

class LibraryName(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name = ... # type: typing___Text

    @property
    def meta(self) -> common_pb2___Metadata: ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        meta : typing___Optional[common_pb2___Metadata] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> LibraryName: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> LibraryName: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"meta",b"meta"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"meta",b"meta",u"name",b"name"]) -> None: ...
