# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ref.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2
from . import name_pb2 as name__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ref.proto',
  package='edg.ref',
  syntax='proto3',
  serialized_pb=_b('\n\tref.proto\x12\x07\x65\x64g.ref\x1a\x0c\x63ommon.proto\x1a\nname.proto\"P\n\tLocalStep\x12+\n\x0ereserved_param\x18\x01 \x01(\x0e\x32\x11.edg.ref.ReservedH\x00\x12\x0e\n\x04name\x18\x03 \x01(\tH\x00\x42\x06\n\x04step\"S\n\tLocalPath\x12!\n\x05steps\x18\x01 \x03(\x0b\x32\x12.edg.ref.LocalStep\x12#\n\x04meta\x18\xff\x01 \x01(\x0b\x32\x14.edg.common.Metadata\"\xa0\x01\n\x0bLibraryPath\x12$\n\x05start\x18\x01 \x01(\x0b\x32\x15.edg.name.LibraryName\x12\"\n\x05steps\x18\x02 \x03(\x0b\x32\x13.edg.name.Namespace\x12\"\n\x06target\x18\x03 \x01(\x0b\x32\x12.edg.ref.LocalStep\x12#\n\x04meta\x18\xff\x01 \x01(\x0b\x32\x14.edg.common.Metadata*?\n\x08Reserved\x12\r\n\tUNDEFINED\x10\x00\x12\x12\n\x0e\x43ONNECTED_LINK\x10\x01\x12\x10\n\x0cIS_CONNECTED\x10(b\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,name__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_RESERVED = _descriptor.EnumDescriptor(
  name='Reserved',
  full_name='edg.ref.Reserved',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECTED_LINK', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IS_CONNECTED', index=2, number=40,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=378,
  serialized_end=441,
)
_sym_db.RegisterEnumDescriptor(_RESERVED)

Reserved = enum_type_wrapper.EnumTypeWrapper(_RESERVED)
UNDEFINED = 0
CONNECTED_LINK = 1
IS_CONNECTED = 40



_LOCALSTEP = _descriptor.Descriptor(
  name='LocalStep',
  full_name='edg.ref.LocalStep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reserved_param', full_name='edg.ref.LocalStep.reserved_param', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='edg.ref.LocalStep.name', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='step', full_name='edg.ref.LocalStep.step',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=48,
  serialized_end=128,
)


_LOCALPATH = _descriptor.Descriptor(
  name='LocalPath',
  full_name='edg.ref.LocalPath',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='steps', full_name='edg.ref.LocalPath.steps', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='meta', full_name='edg.ref.LocalPath.meta', index=1,
      number=255, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=213,
)


_LIBRARYPATH = _descriptor.Descriptor(
  name='LibraryPath',
  full_name='edg.ref.LibraryPath',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='edg.ref.LibraryPath.start', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='steps', full_name='edg.ref.LibraryPath.steps', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target', full_name='edg.ref.LibraryPath.target', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='meta', full_name='edg.ref.LibraryPath.meta', index=3,
      number=255, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=376,
)

_LOCALSTEP.fields_by_name['reserved_param'].enum_type = _RESERVED
_LOCALSTEP.oneofs_by_name['step'].fields.append(
  _LOCALSTEP.fields_by_name['reserved_param'])
_LOCALSTEP.fields_by_name['reserved_param'].containing_oneof = _LOCALSTEP.oneofs_by_name['step']
_LOCALSTEP.oneofs_by_name['step'].fields.append(
  _LOCALSTEP.fields_by_name['name'])
_LOCALSTEP.fields_by_name['name'].containing_oneof = _LOCALSTEP.oneofs_by_name['step']
_LOCALPATH.fields_by_name['steps'].message_type = _LOCALSTEP
_LOCALPATH.fields_by_name['meta'].message_type = common__pb2._METADATA
_LIBRARYPATH.fields_by_name['start'].message_type = name__pb2._LIBRARYNAME
_LIBRARYPATH.fields_by_name['steps'].message_type = name__pb2._NAMESPACE
_LIBRARYPATH.fields_by_name['target'].message_type = _LOCALSTEP
_LIBRARYPATH.fields_by_name['meta'].message_type = common__pb2._METADATA
DESCRIPTOR.message_types_by_name['LocalStep'] = _LOCALSTEP
DESCRIPTOR.message_types_by_name['LocalPath'] = _LOCALPATH
DESCRIPTOR.message_types_by_name['LibraryPath'] = _LIBRARYPATH
DESCRIPTOR.enum_types_by_name['Reserved'] = _RESERVED

LocalStep = _reflection.GeneratedProtocolMessageType('LocalStep', (_message.Message,), dict(
  DESCRIPTOR = _LOCALSTEP,
  __module__ = 'ref_pb2'
  # @@protoc_insertion_point(class_scope:edg.ref.LocalStep)
  ))
_sym_db.RegisterMessage(LocalStep)

LocalPath = _reflection.GeneratedProtocolMessageType('LocalPath', (_message.Message,), dict(
  DESCRIPTOR = _LOCALPATH,
  __module__ = 'ref_pb2'
  # @@protoc_insertion_point(class_scope:edg.ref.LocalPath)
  ))
_sym_db.RegisterMessage(LocalPath)

LibraryPath = _reflection.GeneratedProtocolMessageType('LibraryPath', (_message.Message,), dict(
  DESCRIPTOR = _LIBRARYPATH,
  __module__ = 'ref_pb2'
  # @@protoc_insertion_point(class_scope:edg.ref.LibraryPath)
  ))
_sym_db.RegisterMessage(LibraryPath)


# @@protoc_insertion_point(module_scope)
