M48
; DRILL file {KiCad (6.0.7)} date Thu Feb 23 11:47:36 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-23T11:47:36-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0454
%
G90
G05
T1
X4.3545Y-1.5791
X4.3545Y-1.8067
T2
X4.1732Y-1.4173
X4.1732Y-2.7953
X6.5354Y-1.4173
T0
M30
