"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
* Defines messages for a service that provides EDG compilation services.
Interface to the HDL (eg, library fetch) is not included here.

This no longer uses gRPC to avoid complexity of sockets.
"""

from collections import abc as _abc
from edgir import lit_pb2 as _lit_pb2
from edgir import ref_pb2 as _ref_pb2
from edgir import schema_pb2 as _schema_pb2
from edgrpc import hdl_pb2 as _hdl_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias
DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ErrorRecord(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor
    PATH_FIELD_NUMBER: _builtins.int
    KIND_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    DETAILS_FIELD_NUMBER: _builtins.int
    kind: _builtins.str
    "kind of error, eg failed to generate"
    name: _builtins.str
    "constraint name / short description"
    details: _builtins.str
    "longer description, optional"

    @_builtins.property
    def path(self) -> _ref_pb2.LocalPath:
        """link / block / port, cannot be the constraint"""

    def __init__(
        self,
        *,
        path: _ref_pb2.LocalPath | None = ...,
        kind: _builtins.str = ...,
        name: _builtins.str = ...,
        details: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["path", b"path"]

    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "details", b"details", "kind", b"kind", "name", b"name", "path", b"path"
    ]

    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ErrorRecord: _TypeAlias = ErrorRecord

@_typing.final
class CompilerRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor
    DESIGN_FIELD_NUMBER: _builtins.int
    REFINEMENTS_FIELD_NUMBER: _builtins.int

    @_builtins.property
    def design(self) -> _schema_pb2.Design: ...
    @_builtins.property
    def refinements(self) -> _hdl_pb2.Refinements: ...
    def __init__(
        self, *, design: _schema_pb2.Design | None = ..., refinements: _hdl_pb2.Refinements | None = ...
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["design", b"design", "refinements", b"refinements"]

    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["design", b"design", "refinements", b"refinements"]

    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CompilerRequest: _TypeAlias = CompilerRequest

@_typing.final
class CompilerResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Value(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor
        PATH_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int

        @_builtins.property
        def path(self) -> _ref_pb2.LocalPath: ...
        @_builtins.property
        def value(self) -> _lit_pb2.ValueLit: ...
        def __init__(self, *, path: _ref_pb2.LocalPath | None = ..., value: _lit_pb2.ValueLit | None = ...) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["path", b"path", "value", b"value"]

        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["path", b"path", "value", b"value"]

        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    DESIGN_FIELD_NUMBER: _builtins.int
    ERRORS_FIELD_NUMBER: _builtins.int
    SOLVEDVALUES_FIELD_NUMBER: _builtins.int

    @_builtins.property
    def design(self) -> _schema_pb2.Design: ...
    @_builtins.property
    def errors(self) -> _containers.RepeatedCompositeFieldContainer[Global___ErrorRecord]: ...
    @_builtins.property
    def solvedValues(self) -> _containers.RepeatedCompositeFieldContainer[Global___CompilerResult.Value]: ...
    def __init__(
        self,
        *,
        design: _schema_pb2.Design | None = ...,
        errors: _abc.Iterable[Global___ErrorRecord] | None = ...,
        solvedValues: _abc.Iterable[Global___CompilerResult.Value] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["design", b"design"]

    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "design", b"design", "errors", b"errors", "solvedValues", b"solvedValues"
    ]

    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CompilerResult: _TypeAlias = CompilerResult
