# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: edgir/lit.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from edgir import common_pb2 as edgir_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65\x64gir/lit.proto\x12\tedgir.lit\x1a\x12\x65\x64gir/common.proto\"\x17\n\x08\x46loatLit\x12\x0b\n\x03val\x18\x01 \x01(\x01\"\x15\n\x06IntLit\x12\x0b\n\x03val\x18\x01 \x01(\x12\"\x16\n\x07\x42oolLit\x12\x0b\n\x03val\x18\x01 \x01(\x08\"\x16\n\x07TextLit\x12\x0b\n\x03val\x18\x01 \x01(\t\"V\n\x08RangeLit\x12$\n\x07minimum\x18\x01 \x01(\x0b\x32\x13.edgir.lit.ValueLit\x12$\n\x07maximum\x18\x02 \x01(\x0b\x32\x13.edgir.lit.ValueLit\"\x84\x01\n\tStructLit\x12\x32\n\x07members\x18\x01 \x03(\x0b\x32!.edgir.lit.StructLit.MembersEntry\x1a\x43\n\x0cMembersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.edgir.lit.ValueLit:\x02\x38\x01\"\xa0\x02\n\x08ValueLit\x12\'\n\x08\x66loating\x18\x01 \x01(\x0b\x32\x13.edgir.lit.FloatLitH\x00\x12$\n\x07integer\x18\x02 \x01(\x0b\x32\x11.edgir.lit.IntLitH\x00\x12%\n\x07\x62oolean\x18\x03 \x01(\x0b\x32\x12.edgir.lit.BoolLitH\x00\x12\"\n\x04text\x18\x04 \x01(\x0b\x32\x12.edgir.lit.TextLitH\x00\x12&\n\x06struct\x18\t \x01(\x0b\x32\x14.edgir.lit.StructLitH\x00\x12$\n\x05range\x18\n \x01(\x0b\x32\x13.edgir.lit.RangeLitH\x00\x12$\n\x04meta\x18\x7f \x01(\x0b\x32\x16.edgir.common.MetadataB\x06\n\x04typeb\x06proto3')



_FLOATLIT = DESCRIPTOR.message_types_by_name['FloatLit']
_INTLIT = DESCRIPTOR.message_types_by_name['IntLit']
_BOOLLIT = DESCRIPTOR.message_types_by_name['BoolLit']
_TEXTLIT = DESCRIPTOR.message_types_by_name['TextLit']
_RANGELIT = DESCRIPTOR.message_types_by_name['RangeLit']
_STRUCTLIT = DESCRIPTOR.message_types_by_name['StructLit']
_STRUCTLIT_MEMBERSENTRY = _STRUCTLIT.nested_types_by_name['MembersEntry']
_VALUELIT = DESCRIPTOR.message_types_by_name['ValueLit']
FloatLit = _reflection.GeneratedProtocolMessageType('FloatLit', (_message.Message,), {
  'DESCRIPTOR' : _FLOATLIT,
  '__module__' : 'edgir.lit_pb2'
  # @@protoc_insertion_point(class_scope:edgir.lit.FloatLit)
  })
_sym_db.RegisterMessage(FloatLit)

IntLit = _reflection.GeneratedProtocolMessageType('IntLit', (_message.Message,), {
  'DESCRIPTOR' : _INTLIT,
  '__module__' : 'edgir.lit_pb2'
  # @@protoc_insertion_point(class_scope:edgir.lit.IntLit)
  })
_sym_db.RegisterMessage(IntLit)

BoolLit = _reflection.GeneratedProtocolMessageType('BoolLit', (_message.Message,), {
  'DESCRIPTOR' : _BOOLLIT,
  '__module__' : 'edgir.lit_pb2'
  # @@protoc_insertion_point(class_scope:edgir.lit.BoolLit)
  })
_sym_db.RegisterMessage(BoolLit)

TextLit = _reflection.GeneratedProtocolMessageType('TextLit', (_message.Message,), {
  'DESCRIPTOR' : _TEXTLIT,
  '__module__' : 'edgir.lit_pb2'
  # @@protoc_insertion_point(class_scope:edgir.lit.TextLit)
  })
_sym_db.RegisterMessage(TextLit)

RangeLit = _reflection.GeneratedProtocolMessageType('RangeLit', (_message.Message,), {
  'DESCRIPTOR' : _RANGELIT,
  '__module__' : 'edgir.lit_pb2'
  # @@protoc_insertion_point(class_scope:edgir.lit.RangeLit)
  })
_sym_db.RegisterMessage(RangeLit)

StructLit = _reflection.GeneratedProtocolMessageType('StructLit', (_message.Message,), {

  'MembersEntry' : _reflection.GeneratedProtocolMessageType('MembersEntry', (_message.Message,), {
    'DESCRIPTOR' : _STRUCTLIT_MEMBERSENTRY,
    '__module__' : 'edgir.lit_pb2'
    # @@protoc_insertion_point(class_scope:edgir.lit.StructLit.MembersEntry)
    })
  ,
  'DESCRIPTOR' : _STRUCTLIT,
  '__module__' : 'edgir.lit_pb2'
  # @@protoc_insertion_point(class_scope:edgir.lit.StructLit)
  })
_sym_db.RegisterMessage(StructLit)
_sym_db.RegisterMessage(StructLit.MembersEntry)

ValueLit = _reflection.GeneratedProtocolMessageType('ValueLit', (_message.Message,), {
  'DESCRIPTOR' : _VALUELIT,
  '__module__' : 'edgir.lit_pb2'
  # @@protoc_insertion_point(class_scope:edgir.lit.ValueLit)
  })
_sym_db.RegisterMessage(ValueLit)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STRUCTLIT_MEMBERSENTRY._options = None
  _STRUCTLIT_MEMBERSENTRY._serialized_options = b'8\001'
  _FLOATLIT._serialized_start=50
  _FLOATLIT._serialized_end=73
  _INTLIT._serialized_start=75
  _INTLIT._serialized_end=96
  _BOOLLIT._serialized_start=98
  _BOOLLIT._serialized_end=120
  _TEXTLIT._serialized_start=122
  _TEXTLIT._serialized_end=144
  _RANGELIT._serialized_start=146
  _RANGELIT._serialized_end=232
  _STRUCTLIT._serialized_start=235
  _STRUCTLIT._serialized_end=367
  _STRUCTLIT_MEMBERSENTRY._serialized_start=300
  _STRUCTLIT_MEMBERSENTRY._serialized_end=367
  _VALUELIT._serialized_start=370
  _VALUELIT._serialized_end=658
# @@protoc_insertion_point(module_scope)
