# Based on https://www.scala-sbt.org/1.x/docs/GitHub-Actions-with-sbt.html
# optimization: https://github.com/marketplace/actions/skip-duplicate-actions#usage-examples

name: Scala PR build and tests

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - id: skip_check
      uses: fkirc/skip-duplicate-actions@master
      with:
        paths: '["**.scala"]'

  mypy:
    needs: pre_job
#    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 8

    - name: sbt test
      run: sbt -v +test
