# Based on https://www.scala-sbt.org/1.x/docs/GitHub-Actions-with-sbt.html
# optimization: https://github.com/marketplace/actions/skip-duplicate-actions#usage-examples

name: Scala PR build and tests

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, ready_for_review]

jobs:
  pre_job:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - id: skip_check
      uses: fkirc/skip-duplicate-actions@master
      with:
        paths: '["compiler/**"]'

  sbt:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17
    - uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - name: install dependencies
      run: |
        pip install protobuf sexpdata Deprecated

    - name: sbt test
      run: cd compiler && sbt -v +test

  scalafmt-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: jrouly/scalafmt-native-action@v2
      with:
        arguments: '--list'
